#!/usr/bin/env python3
"""Generate the B.P3 public/hidden-support inventory from a pinned Git revision.

The handoff is deliberately generated with ``git show REV:path`` instead of the
checkout.  That makes the review artifact continue to describe the frozen
implementation even when this evidence branch accumulates documentation-only
changes.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


IMPLEMENTATION_REVISION = "c31095326bde604557dd1aa51c7252db7b3d6284"


def git_show(root: Path, revision: str, path: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(root), "show", f"{revision}:{path}"], text=True
    )


def resolved_revision(root: Path, revision: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", revision], text=True
    ).strip()


def require(source: str, needle: str, label: str) -> None:
    if needle not in source:
        raise SystemExit(f"inventory source check failed: {label} ({needle!r})")


def markdown(revision: str, sources: dict[str, str]) -> str:
    lib = sources["crates/sc-observability-log/src/lib.rs"]
    control = sources["crates/sc-observability-log/src/control.rs"]
    errors = sources["crates/sc-observability-log/src/error.rs"]
    health = sources["crates/sc-observability-log/src/health.rs"]
    codes = sources["crates/sc-observability-log/src/error_codes.rs"]
    macros = sources["crates/sc-observability-log-macros/src/lib.rs"]

    # These assertions turn this deliberately readable manifest into a source
    # check: adding or removing a named member must update both the source and
    # the inventory before the generator can be used as evidence.
    checks = [
        (lib, "pub use control::{BridgeEvent, EmitOutcome, LogControl};", "control reexports"),
        (lib, "pub use error::{", "error reexports"),
        (lib, "pub use health::{BRIDGE_HEALTH_SCHEMA_VERSION, BridgeHealthReport};", "health reexports"),
        (lib, "pub use sc_observability_log_macros::{debug, error, event, info, instrument, trace, warn};", "macro reexports"),
        (lib, "pub mod __private {", "hidden support module"),
        (lib, "pub use handle::fail_next_shutdown_coordinator_reservation;", "test hook reexport"),
        (control, "pub struct BridgeEvent", "BridgeEvent"),
        (control, "pub struct LogControl", "LogControl"),
        (errors, "pub enum EmitError", "EmitError"),
        (errors, "pub enum DropCause", "DropCause"),
        (health, "pub struct BridgeHealthReport", "BridgeHealthReport"),
        (codes, "pub const ALL: &[ErrorCode]", "error-code registry"),
        (macros, "pub fn instrument", "instrument macro"),
    ]
    for source, needle, label in checks:
        require(source, needle, label)

    return f"""# B.P3 implementation API and macro-support inventory

Generated from implementation revision `{revision}`. Do not edit this file by
hand; regenerate it with:

```text
python3 scripts/generate_bp3_handoff_inventory.py \\
  --revision {IMPLEMENTATION_REVISION} \\
  --output docs/plans/sc-observability-runtime/bp3-implementation-inventory.md
```

The generator reads each listed file with `git show REV:path`, so this artifact
does not accidentally describe the handoff branch. The accepted target and
runtime contracts are `84b32e9d6718418371ffd25a3de52346278725ca`.

## Root contract and re-exports

Every root export/re-export below is retained as the listed target disposition.
`error_codes` is the sole public module; all other implementation modules are
private apart from the exact-version `__private` macro boundary documented
below.

| Root symbol(s) | Source | Target disposition |
| --- | --- | --- |
| `error_codes` | `lib.rs` | Preserve public stable-code registry module. |
| `BridgeEvent`, `EmitOutcome`, `LogControl` | `control.rs` via `lib.rs` | Native direct/control surface; retain non-owning control boundary. |
| `ControlError`, `DropCause`, `EmitError`, `FieldKeyError`, `FlushError`, `InitError`, `LifecyclePhase`, `ShutdownError`, `WaitError`, `ShutdownOutcome`, `ShutdownReport`, `UnconfirmedShutdown` | `error.rs` via `lib.rs` | Retain native typed, serde-tagged errors and retained completion observation. |
| `BRIDGE_HEALTH_SCHEMA_VERSION`, `BridgeHealthReport` | `health.rs` via `lib.rs` | Retain native bridge health v1. |
| `LoggerConfig` | `sc_observability` via `lib.rs` | Re-export the staged-core configuration rather than an adapter. |
| `ActionName`, `CorrelationId`, `ErrorCode`, `LevelFilter`, `LoggingHealthReport`, `OutcomeLabel`, `ProcessIdentityPolicy`, `Remediation`, `ServiceName`, `TargetCategory`, `Timestamp`, `TraceContext` | `sc_observability_types` via `lib.rs` | Re-export core-neutral contract values. |
| `AdmissionOutcome`, `EventLevel`, `LevelChange`, `LevelChangeError`, `LevelChangeSource`, `LevelState`, `LogEvent`, `LogQuery`, `LogSnapshot`, `OperationDiagnostic` | `sc_observability_types` via `lib.rs` | Re-export staged-core event/query/level contracts; `AdmissionOutcome` is also spelled `EmitOutcome`. |
| `trace!`, `debug!`, `info!`, `warn!`, `error!`, `event!`, `#[instrument]` | `sc-observability-log-macros` via `lib.rs` | Preserve tracing-compatible grammar and exact-version expansion boundary. |
| `init` | `lib.rs` | Retain process-global install returning the sole `LogGuard` lifecycle owner. |
| `Level` (`TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`) | `lib.rs` | Retain tracing-style level API; conversion targets staged-core level. |
| `BridgeOptions` | `lib.rs` | Retain bridge configuration with target-owned action parsing. |
| `DroppedEvents`, `DEFAULT_DROP_SHUTDOWN_TIMEOUT` | `lib.rs` | Retain exact-once drop accounting and bounded implicit teardown contract. |
| `LogGuard` | `lib.rs` | Retain the non-`Clone` lifecycle owner and exclusive level/shutdown authority. |

## Public native data, payloads, derives, and methods

| Symbol | Complete public shape at `{revision}` | Target disposition |
| --- | --- | --- |
| `BridgeEvent` | `#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]`; fields `level`, `target`, `action`, `message`, `outcome`, `fields`, `request_id`, `correlation_id`, `trace` | Retain typed direct producer input; bridge-owned identity/timestamp remain absent. |
| `LogControl` | `#[derive(Debug, Clone)]`; `flush(timeout)`, `health()`, `active_log_path()`, `dropped_events()`, `wait_stopped(timeout)`, `try_log(event)`, `query(query)` | Retain cloneable, non-owning read/admission control; no elevate, reset, shutdown, owner conversion, or mutable logger access. |
| `Level` | `#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]`; associated constants `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`; `From<Level> for sc_observability_types::Level` | Retain fixed tracing-style API and staged-core conversion. |
| `BridgeOptions` | `#[derive(Debug, Clone)]`; public fields `default_action: ActionName`, `parse_bracket_action: bool` | Retain target action/default behavior. |
| `DroppedEvents` | `#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]`; `get(cause)`, `total()` | Retain exact-once counters; fields intentionally remain private. |
| `LogGuard` | `#[derive(Debug)]`, deliberately not `Clone`; `control()`, `elevate_level(level, source)`, `reset_level(source)`, `flush(timeout)`, `shutdown(timeout)`, `dropped_events()`, `active_log_path()`, `health()` | Retain sole ownership of runtime-level mutation and shutdown. |
| `BridgeHealthReport` | `#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]`; public fields `schema_version`, `logging`, `dropped`, `lifecycle`, `active_log_path`, `configured_level`, `effective_level`, `level_revision` | Retain native health v1 with the staged core report and bridge lifecycle/accounting fields. |
| `ShutdownReport` | `#[derive(Debug, Clone, Serialize, Deserialize)]`; public fields `outcome`, `health` | Retain final/pending shutdown observation without claiming an unconfirmed stop. |
| `DropCause` | `#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]`; variants `QueueFull`, `InvalidEvent`, `WriterDegraded`, `ShutdownTimedOut`, `NotInstalled`, `LoggerPanicked`, `ReentrantEmit`; `ALL` | Retain seven exact accounting categories and declaration order. |
| `LifecyclePhase` | `#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]`; variants `Running`, `Stopping`, `Stopped`, `Failed` | Retain observable lifecycle projection. |
| `FieldKeyError` | `#[derive(Debug, Clone, Serialize, Deserialize, Error)]`; variants `Empty`, `ReservedPrefix`, `Collision {{ other_raw_key }}` | Retain typed field-label rejection. |
| `EmitError` | `#[derive(Debug, Clone, Serialize, Deserialize, Error)]`; `InvalidField {{ raw_key, reason }}`, `InvalidEvent {{ diagnostic }}`, `QueueFull {{ diagnostic }}`, `WriterDegraded {{ diagnostic }}`, `ShutdownTimedOut {{ diagnostic }}`, `NotRunning {{ phase }}`, `Reentrant`, `Panicked`; `code()`, `remediation()` | Retain typed direct-admission rejection and exact-once disposition. |
| `ControlError` | `#[derive(Debug, Clone, Serialize, Deserialize, Error)]`; `NotRunning {{ phase }}`, `Query {{ diagnostic }}`, `Unavailable {{ diagnostic }}`; `code()`, `remediation()` | Retain typed read-only control failure. |
| `WaitError` | `#[derive(Debug, Clone, Serialize, Deserialize, Error)]`; `NotStarted`, `TimedOut {{ timeout }}`, `Unavailable {{ diagnostic }}`; `code()`, `remediation()` | Retain owner-shutdown observation failure. |
| `UnconfirmedShutdown` | `#[derive(Debug, Clone, Serialize, Deserialize)]`; `HelperSpawn {{ diagnostic }}`, `HelperLost {{ diagnostic }}` | Retain explicit non-confirmation states. |
| `ShutdownOutcome` | `#[derive(Debug, Clone, Serialize, Deserialize)]`; `Stopped`, `StoppedWithFlushError {{ diagnostic }}`, `Unconfirmed {{ cause }}` | Retain completion truthfulness: unconfirmed is never stopped. |
| `InitError` | `#[derive(Debug, Clone, Serialize, Deserialize, Error)]`; `AlreadyInitialized`, `ForeignLoggerInstalled`, `UnsupportedLevel {{ configured, available }}`, `IdentityResolution {{ diagnostic }}`, `Logger {{ diagnostic }}`, `RuntimeStart {{ diagnostic }}`; `code()`, `remediation()` | Retain typed installation/lifecycle failure. |
| `FlushError` | `#[derive(Debug, Clone, Serialize, Deserialize, Error)]`; `TimedOut {{ timeout }}`, `Logger {{ diagnostic }}`, `HelperSpawn {{ diagnostic }}`, `HelperLost {{ diagnostic }}`, `NotRunning {{ phase }}`, `InProgress`; `code()`, `remediation()` | Retain bounded helper-flush semantics. |
| `ShutdownError` | `#[derive(Debug, Clone, Serialize, Deserialize, Error)]`; `TimedOut {{ timeout }}`, `FinalFlush {{ diagnostic }}`, `HelperSpawn {{ diagnostic }}`, `HelperLost {{ diagnostic }}`; `code()`, `remediation()` | Retain sole-owner bounded shutdown semantics. |

Every enum above that has `Serialize`/`Deserialize` uses its source-declared
snake_case tagged representation (`kind`/`value`) except `LifecyclePhase`,
which uses snake_case unit variants. The API-freeze test at
`crates/sc-observability-log/tests/api_freeze.rs` additionally compiles the
public methods and the promised data/error trait bounds.

## Stable error-code registry

`error_codes::ALL` retains exactly these sixteen codes, in source declaration
order: `SC_OBSERVABILITY_LOG_ALREADY_INITIALIZED`,
`SC_OBSERVABILITY_LOG_FOREIGN_LOGGER_INSTALLED`,
`SC_OBSERVABILITY_LOG_IDENTITY_RESOLUTION_FAILED`,
`SC_OBSERVABILITY_LOG_FLUSH_TIMED_OUT`,
`SC_OBSERVABILITY_LOG_SHUTDOWN_TIMED_OUT`,
`SC_OBSERVABILITY_LOG_HELPER_SPAWN_FAILED`,
`SC_OBSERVABILITY_LOG_HELPER_LOST`, `SC_OBSERVABILITY_LOG_UNSUPPORTED_LEVEL`,
`SC_OBSERVABILITY_LOG_RUNTIME_START_FAILED`, `SC_OBSERVABILITY_LOG_NOT_RUNNING`,
`SC_OBSERVABILITY_LOG_INVALID_FIELD`, `SC_OBSERVABILITY_LOG_REENTRANT_EMIT`,
`SC_OBSERVABILITY_LOG_LOGGER_PANICKED`, `SC_OBSERVABILITY_LOG_STATUS_UNAVAILABLE`,
`SC_OBSERVABILITY_LOG_SHUTDOWN_NOT_STARTED`, and
`SC_OBSERVABILITY_LOG_FLUSH_IN_PROGRESS`. Their disposition is retain: each is
the stable code returned by a native public error rather than an adapter error.

## Hidden exact-version macro support

`__private` is `#[doc(hidden)]` but externally reachable by macro expansion.
It is not a semver API: the root crate pins `sc-observability-log-macros` to an
exact `=` version. Its complete export set at this revision is:

| Hidden symbol(s) | Target disposition |
| --- | --- |
| `serde_json::Map`, `serde_json::Value`, staged-core `Level` | Retain only for generated expansion data assembly. |
| `Callsite`, `DebugKind`, `DebugKindTag`, `DynamicKey`, `FieldDebug`, `FieldRecord`, `FieldValue`, `SerializeKind`, `SerializeKindTag`, `debug_value`, `display_value`, `emit_callsite`, `record_dynamic_field`, `record_field` | Retain exact-version callsite caching and field dispatch. |
| `CallLevels`, `CallOutcome`, `CallSpan`, `Entered`, `current_trace` | Retain exact-version `#[instrument]` context/completion expansion support. |
| `LabelError`, `LabelKind`, `RESERVED_FIELD_PREFIX`, `action_label`, `field_key_label`, `sanitize_label`, `target_label` | Retain one label sanitizer and reserved-prefix rule for macros. |
| `EventParts` (`#[derive(Debug)]`; public fields `level`, `target`, `action`, `message`, `outcome`, `fields`) | Retain generated event assembly only. |
| `enabled(level)`, `emit(parts)`, `record_drop(cause)` | Retain guarded filter/submit/accounting dispatch only. |

## Feature-gated test-only export

`#[cfg(feature = "test_hooks")] #[doc(hidden)]`
`fail_next_shutdown_coordinator_reservation` is the only feature-gated root
item. Its disposition is retain as test-only deterministic lifecycle fault
injection; it is excluded from normal production feature resolution.

## Removed surface confirmation

The source task's required removals remain absent at this revision:
`report.rs`, `StructuredRecord`, `SubmitOutcome`, `SubmitError`,
`FailureReport`, `CONTROL_SCHEMA_VERSION`, `THRESHOLD`, `THRESHOLD_OFF`,
`encode_threshold`, `level_enabled`, and `to_log_level_filter`. The target
disposition for every listed spelling is removed; the source handoff's
whole-crate scan is recorded separately in the validation evidence.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--revision", default=IMPLEMENTATION_REVISION)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    revision = resolved_revision(root, args.revision)
    if revision != IMPLEMENTATION_REVISION:
        raise SystemExit(
            f"expected implementation revision {IMPLEMENTATION_REVISION}, got {revision}"
        )
    paths = [
        "crates/sc-observability-log/src/lib.rs",
        "crates/sc-observability-log/src/control.rs",
        "crates/sc-observability-log/src/error.rs",
        "crates/sc-observability-log/src/health.rs",
        "crates/sc-observability-log/src/error_codes.rs",
        "crates/sc-observability-log-macros/src/lib.rs",
    ]
    sources = {path: git_show(root, revision, path) for path in paths}
    output = markdown(revision, sources)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output)


if __name__ == "__main__":
    main()
